using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlackJack_Black_Edition_0._0._6
{
    static class Funcoes
    {

        static bool Confirmar(bool Verficardor) //Verificar ele recebe um valor e retorna ou um falso ou true
        {
            if (Verficardor) { return true; } //Retorna vdd
            return false; //Retorna fake
        }
    }
}
